let a = 5;
const b = '6';
const c = 7;
const d = '7';
const d1 = 'Hello';

console.log(a + b);
console.log(a + c);
console.log(a - b);
console.log(b + d);
console.log(b - d1, typeof (b - d1));
console.log(a * b);
console.log(a / b);
console.log(a % b);
console.log(a ** b);
a += a;
console.log(a);
a -= a;
console.log(a);
a = 5;
a *= a;
console.log(a);
a /= a;
console.log(a);
a %= a;
console.log(a);
a **= a;
console.log(a);
